### ISSUE TITLE
[Insurgency] Insurgent spawn points don't show the associated control point

### ISSUE THREAD

**Issue by frenchiveruti** [ata4/bspsrc#100]
Hi, I've decompiled a map made for insurgency, that has all spawnpoints for the insurgent forces but lacks the associated points from them.  
![imagen](https://user-images.githubusercontent.com/1095997/80268666-a545b900-867f-11ea-9fc1-acc5dabfc26f.png)
As you can see, it's blank.  
Maybe I'm missing something. But I believe that should be filled.  
Thanks

**Comment by rihi** [comment]
I'm not really familiar with the game, so I don't really know how mapping for it works.
That said though, I looked into the map in question and was able to verify that the actual spawnpoint entities in the bsp were already missing this tag.
So either the information is stored somewhere different or this is actually intended.

**Comment by frenchiveruti** [comment]
Hi, thanks for reminding me about this.  
Indeed the game works different, it's just a spawnpoint INSIDE a spawnzone that "links" them, so an insurgent needs to be INSIDE a spawnzone to be "linked" to a certain map checkpoint.  
No issue here.
