### ISSUE TITLE
CS:GO Static props missing keyvalues

### ISSUE THREAD

**Issue by Darnias** [ata4/bspsrc#102]
Some prop_static keyvalues are lost when decompiled. Not sure if they are retrievable from the lumps or lost forever. I'm providing source model and decompiled for comparison. The important one is "Ignore Surface Normal" and maybe "Enable Bounced Lighting". Thanks for considering any options!
[Decompiled](https://i.imgur.com/sOLCJRg.png)
[Original](https://i.imgur.com/JyiZytn.png)

**Comment by rihi** [comment]
`Ignore Surface Normal` not being set is a simple oversight in the code, which I've fixed in #110.
`Enable Bounced Lighting` on the other hand is sadly not related to that bug. I'll see if I can find the reason for it not working.

**Comment by rihi** [comment]
The fix has now been released with version 1.4.1.
As far as I know, `Enable Bounced Lighting` sadly can't be correctly set, as that information is basically "lost" on compilation.

**Comment by SirYodaJedi** [comment]
Bounced lighting is set via the `flagsEx` bitfield. Known values are:
* `0x1` - `disableshadowdepth` KV
* `0x2` - disables CSM; I don't think there's a KV for this
* `0x4` - `enablelightbounce` KV

**Comment by rihi** [comment]
Thanks for the info! I've implemented the remaining flags with b1eb1688, which will be included the next release.
