### ISSUE TITLE
Clip brushes get written as skip brushes

### ISSUE THREAD

**Issue by mikkokko** [ata4/bspsrc#111]
Occured when decompiling some CS:S maps, namely cs_assault, cs_havana, de_cbble and de_tides.

**Comment by rihi** [comment]
This has been fixed with the new 1.4.0 version.
If your problem is not resolve with that new version, feel free to write here and I'll have another look at the problem.
You can get the release on the [releases page](https://github.com/ata4/bspsrc/releases).
