### ISSUE TITLE
No way to open bsprc

### ISSUE THREAD

**Issue by okkward** [ata4/bspsrc#112]
i open the zip and there is no executable or jar, plz help

**Comment by yuripourre** [comment]
@okkward 
Are you sure you downloaded the right zip?
The one in the latest relase has a jar and a bat file.

**Comment by rihi** [comment]
You have probably accidentally downloaded the source code instead of the compiled binaries.
You can find them on the [release](https://github.com/ata4/bspsrc/releases) page.

**Comment by Gracefulmender** [comment]
You have to uninstall WinRAR and 7-Zip, then download the Java runtime.

**Comment by rihi** [comment]
The [Readme](https://github.com/ata4/bspsrc/tree/v1.4.3#running-bspsource) now contains instruction of how to run bspsrc.
If you still have problems, feel free to answer.
