### ISSUE TITLE
4-way texture blends don't decompile properly

### ISSUE THREAD

**Issue by TJHL** [ata4/bspsrc#114]
Displacements with 4-way blends seem to only have their base texture applied to the entire displacement.

I'm pretty sure this is because bspsrc doesn't recognize 4-way blends to be a thing.

**Comment by rihi** [comment]
If tested this with a simple map and sadly couldn't reproduce your problem. Can you share the map you tried decompiling so I could have a look at it?

**Comment by TJHL** [comment]
This is for Black Mesa, try `bm_c2a5a`, `bm_c2a5c` or literally any of the xen maps.
