### ISSUE TITLE
Unable to build with Maven

### ISSUE THREAD

**Issue by VaasKahnGrim** [ata4/bspsrc#120]
So currently I have Maven 3.6.3 on my PC, JDK SE 15 installed and I've downloaded a fresh copy of bspsrc from this repo.
I have 2 logs, one with the pom.xml unaltered, and another where I had removed `<release>8</release>` to try and resolve an issue I had

log with unaltered pom.xml: https://pastebin.com/DSF6e46z
log after deleting the release portion from pom.xml: https://pastebin.com/zfMBva5u

I'm at a loss on how to fix this thing or get it to actually compile. As far as I'm aware, I've installed Maven and JDK correctly.

**Comment by rihi** [comment]
Your maven is probably still using an older version of java. The `release` option was only added with java 9.
As far as I know, maven just uses whatever version is in PATH, so you should be able to test which version is used by executing `java -version`.

**Comment by VaasKahnGrim** [comment]
![image](https://user-images.githubusercontent.com/29955667/105555091-483e6880-5cce-11eb-97a1-56942d6fae7e.png)


Java 15 I think

**Comment by VaasKahnGrim** [comment]
![image](https://user-images.githubusercontent.com/29955667/105555493-1f6aa300-5ccf-11eb-8db6-20aafff470d8.png)
sorry for a second response but figured I'd also send the javac and maven version info aswell

**Comment by rihi** [comment]
Yeah, your maven is using a java 8 installation. I've looked it up and it's not the `PATH` variable, but rather `JAVA_HOME` which maven uses to locate java. So you would need to change that enviroment variable to your java 15 installation.

**Comment by VaasKahnGrim** [comment]
well it builds successfully now but I can't seem to find the .jar for it

**Comment by VaasKahnGrim** [comment]
nvm, apparently there are two seperate commands needed because maven decided on being autistic. either way thank you for the help with figuring out the issue
