### ISSUE TITLE
i cant open bsp source

### ISSUE THREAD

**Issue by aaaaaaaaaa2** [ata4/bspsrc#121]
when i try to open the .bat file it says that windows couldn't open it.
![Screenshot (1)](https://user-images.githubusercontent.com/77898703/105612529-b6f5f180-5db4-11eb-953a-a2d50c0fc96a.png)

**Comment by rihi** [comment]
You probably don't have java installed. Bspsrc requires java 8 or higher.

**Comment by aaaaaaaaaa2** [comment]
> You probably don't have java installed. Bspsrc requires java 8 or higher.

ok i will do that

**Comment by aaaaaaaaaa2** [comment]
> You probably don't have java installed. Bspsrc requires java 8 or higher.

ok it works now thanks
