### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by noonesgonnasayyouraoki** [ata4/bspsrc#124]
whenever i try to launch bspsrc it says it cant find "javaw"

**Comment by notcat** [comment]
Download Java.

**Comment by rihi** [comment]
Yeah, you have to have java installed, to run this application. See the [Readme](https://github.com/ata4/bspsrc/tree/v1.4.3#running-bspsource).
Incase you do actually have java installed, there was also an issue with the linux start script which has now been fixed with version 1.4.3.
