### ISSUE TITLE
Split client from library and upload to Maven Central

### ISSUE THREAD

**Issue by iTitus** [ata4/bspsrc#125]
It would be nice to have the library portion of this application available on Maven Central and the minimal front-end (gui/cli) to be just a little wrapper that calls functions from that library and redirects the log.

The split is nearly there already, but the decompilation&analysis is still only available to `bspsrc`

**Comment by rihi** [comment]
I thought about doing this some time ago already. I think it would be beneficial for the overall code quality and would present some interesting opportunities (Potential of bundled runtime, jlink, possibility to use higher java versions).

However, trying to do this through Pull request seems very unrealistic in my opinion. At least at the time, with the amount of changes this would produce and with the amount of other pull request already existing, it would be an absolute pain to merge.

**Comment by Degubi** [comment]
In my fork I separated bspsrc into 1 library and 2 applications:
- BSPLib (Library files that the other 2 applications depend on)
- BSPInfo (Info visualizer)
- BSPDecomp (Decompiler)

Also created a python script that builds the original bundle with a custom jre. (Updated & modularized all code to java11)
Fork: https://github.com/Degubi/bspsrc

**Comment by rihi** [comment]
With the newest version, I have also split the application into multiple modules like suggest by the issue.
The codebase is not structured into 4 modules:
- **bspsrc-common**: Internal code, depended on by all other modules.
- **bspsrc-lib**: BSP loading and parsing.
- **bspsrc-decompiler**: Code for actual decompilation to VMF.
- **bspsrc-app**: CLI/GUI build on top of decompiler.

These modules can now also be used as maven dependencies using [JitPack](https://jitpack.io/). The artifact coordinates should be `com.github.ata4.bspsrc:<module-name>:<version>`. Version can either be a concrete version like 1.4.4 or a commit sha1 like `15cbc66fb1`. Note using concrete version numbers does not currently work and will only start for the next version like 1.4.5. For that duration either use the commit sha1 or 'master-SNAPSHOT' if you always want the newest version
