### ISSUE TITLE
GUI broken

### ISSUE THREAD

**Issue by MXYLR** [ata4/bspsrc#130]
![D776 (WPEZK}2{~4JZZS8)H](https://user-images.githubusercontent.com/37480216/124538266-e9b91100-de4d-11eb-9f90-90d32e785259.png)

**Comment by ata4** [comment]
Okay, looks like the font is unusually large here. Can you make the buttons more visible by changing the window size manually?

**Comment by MXYLR** [comment]
No I tried that and didnt work, but older version doesnt have this issue

**Comment by Co1or** [comment]
2 solutions:
1.install latest [JRE8](https://www.oracle.com/java/technologies/javase-jre8-downloads.html)
2.set 100% scale display

**Comment by rihi** [comment]
This was fixed with version [1.4.4](https://github.com/ata4/bspsrc/releases).
