### ISSUE TITLE
Decompile button doesn't work on linux

### ISSUE THREAD

**Issue by Keldraistaken** [ata4/bspsrc#139]
I'm using arch linux with liquorix kernel, java 17.0.1.

I'm able to select a file to decompile however the menu to choose the location for the decompiled file and it's contents doesn't show up

**Comment by rihi** [comment]
Hm, I'm not sure what could be causing your issue.
Could you try launching the gui from the command line and see if any error message is being output?

**Comment by Keldraistaken** [comment]
![image](https://user-images.githubusercontent.com/45337750/146809414-a0b3311b-17e4-4c2c-9ebc-27dd1bfb1add.png)

Here you go

**Comment by Keldraistaken** [comment]
Also I'll try switching to java 8

**Comment by Keldraistaken** [comment]
Well I took a look at the code, I couldn't find any issues. However when I compiled it myself with `mvn package` it worked fine so I'll close the issue but you might want to look into it further for the file in the releases section.
