### ISSUE TITLE
Texture Alignment is Broken

### ISSUE THREAD

**Issue by TheKins** [ata4/bspsrc#14]
I first noticed this bug in 1.3.18, but I'm not sure how far back it goes.

Run [this map](https://dl.dropboxusercontent.com/u/25843724/temp/gm_highriseapartment.bsp) through BSPSrc. Open it up in Hammer and look at the texture alignments on the walls, doors and cabinet. This appears to have broken recently, as it's not happening in the older version I keep around.

**Comment by ata4** [comment]
Ah darn, the floating point decimals are truncated to one digit, so the default texture scale is 0.2 instead of 0.25. I should not have touched that VMF writer class... I'll upload a fix tomorrow.

**Comment by TheKins** [comment]
Thank you very much!
