### ISSUE TITLE
CS16, HLA maps

### ISSUE THREAD

**Issue by eminem0091** [ata4/bspsrc#144]
Hello, will work in future of bspsrc decompiling maps for cs16 and half life alyx? 

Thank you

EMINEM :)

**Comment by rihi** [comment]
CS 1.6 uses the goldsrc engine which has a inherently different map format from the normal source engine, which bspsrc is decompiling. I'm not to familiar with it myself, but I think there are some older decompilers which support the goldsrc engine.

Half-Life: Alyx on the other hand was made in Valves new engine called Source 2. To open/view files of it, you can use [ValveResourceFormat](https://github.com/SteamDatabase/ValveResourceFormat).
