### ISSUE TITLE
Playerclip texture as "tools/toolsskip" texture after decompile map

### ISSUE THREAD

**Issue by eminem0091** [ata4/bspsrc#145]
Hello, after decompiling cs_assault I do not have any playerclip textures.. Instead I have skip textures

r_drawclipbrushes 1

tools/toolsskip

![obrazek](https://user-images.githubusercontent.com/20126321/159558501-13e6781e-53d0-4eb9-a2af-403d1d2a2f13.png)
![obrazek](https://user-images.githubusercontent.com/20126321/159558561-061ffb1a-2774-456d-946e-9348c910aacd.png)

**Comment by rihi** [comment]
Thanks for reporting the issue. For some reason, css behaves differently and more inconsistently from other games, which causes this bug to happen.
I've fixed this in a recent commit, so the bug should be gone in the next release.
