### ISSUE TITLE
Add bypass for decomiple map

### ISSUE THREAD

**Issue by Shesui** [ata4/bspsrc#146]
Add deObsufecator for obsufacted map

**Comment by worMatty** [comment]
What do you mean?

**Comment by rihi** [comment]
In general, bspsrc will try to decompile all maps no matter how obfuscated they were. Often these anti decompiler methods use the fact, that to play the bsp, the game needs far less info than what is contained in it. Bspsrc however, often relies on that info. This often means that information is simply lost with anti decompilation measures.

If you have any specific issues with any maps, feel free to open an issue.
