### ISSUE TITLE
[L4D1/2] Ladder brushes being duplicated bug

### ISSUE THREAD

**Issue by Shadowysn** [ata4/bspsrc#147]
This has been a problem since version 1.3.19, yet nobody, _NOBODY_ from L4D modding/mapping has decided to report it.
I'm looking at you, a certain Tsu-name person.

Steps to reproduce:
1. Decompile a L4D1/2 map.
2. In Hammer, find a ladder brush in the decompiled vmf.
3. Move a ladder brush out of it's position to see the duplicate ladder brush.

![ladder_bug](https://user-images.githubusercontent.com/44493487/170714982-87381bcb-fc03-4479-96c3-ded752e66b14.PNG)

**Comment by rihi** [comment]
Thanks for reporting the issue. It should be fixed now with new version 1.4.3.
You can get the release on the [releases page](https://github.com/ata4/bspsrc/releases).
