### ISSUE TITLE
Half-Life 2: Episode One

### ISSUE THREAD

**Issue by KrazyKasrkin** [ata4/bspsrc#15]
Just a heads up, it appears some Half-Life 2: Episode One maps fail to compile in version 1.3.20 (default settings)
Last version I used to decompile ep1 successfully was 1.3.13

##### Output snippet for ep1_citadel_00 (with lmp):
[info] Loading D:\Steam\steamapps\common\Half-Life 2\episodic\maps\ep1_citadel_00_demo.bsp
[warning] BspFile: Invalid lump length 168,671,624 in LUMP_LEAF_AMBIENT_LIGHTING_HDR, assuming 35,261,906
[warning] BspFile: Invalid lump offset 195,636,224 in LUMP_LEAF_AMBIENT_LIGHTING, assuming 36,831,594
[warning] BspFile: Invalid lump offset 1,373,088,768 in LUMP_FACES_HDR, assuming 36,831,594
[warning] BspFile: Negative lump offset -1,669,490,688 in LUMP_MAP_FLAGS, assuming 0
[warning] BspFile: Negative lump offset -1,660,539,904 in LUMP_OVERLAY_FADES, assuming 0
[warning] BspFile: Invalid game lump offset 2,097,184 in <dummy>, assuming 22,494

...

[error] BspFile: Couldn't load game lumps, caused by java.io.EOFException
	at info.ata4.io.buffer.ByteBufferDataInput.readInt(ByteBufferDataInput.java:116)
	at info.ata4.io.DataInputBridge.readInt(DataInputBridge.java:86)
	at info.ata4.bsplib.BspFile.loadGameLumps(BspFile.java:535)
	at info.ata4.bsplib.BspFile.load(BspFile.java:159)
	at info.ata4.bsplib.BspFile.load(BspFile.java:178)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:98)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:67)
	at info.ata4.bspsrc.gui.BspSourceFrame$5.run(BspSourceFrame.java:362)

[error] BspSourceFrame: Fatal BSPSource error, caused by java.lang.OutOfMemoryError: Requested array size exceeds VM limit

--

On Java 7: 7.1

Thanks!

**Comment by ata4** [comment]
Well, that mysterious map appears to be broken. HL2 can't load it, so it can't be decompiled either. I tried to fix it manually by hand, but I couldn't get together more than a few fragments. The whole lump table is messed up and there are random bytes everywhere that shouldn't be there.
