### ISSUE TITLE
Incorrect grenade clip decompilation

### ISSUE THREAD

**Issue by PiMoNFeeD** [ata4/bspsrc#153]
Starting with v1.4.1, bspsrc decompiles some nodraw faces as grenade clips
As an example, de_vertigo with `r_drawclipbrushes 3` inside mid ceiling (all featured solids are func_breakables)
![image](https://user-images.githubusercontent.com/36343425/195155270-57977516-d9eb-4cd4-a8ea-f7a4da94e651.png)
![image](https://user-images.githubusercontent.com/36343425/195155306-d648a900-ed91-444a-a628-b51a803c6117.png)
Another example would be wingman blocker brushes, their sides have grenade clips for whatever reason instead of nodraws like on any other map
v1.4.0 (which introduced grenade clip support in the first place) doesn't have such a problem

**Comment by rihi** [comment]
The issue should now been fixed with version 1.4.3.
You can get the new release on the [releases page](https://github.com/ata4/bspsrc/releases).
