### ISSUE TITLE
I can't open bspsrc.

### ISSUE THREAD

**Issue by Koniglich** [ata4/bspsrc#156]
Hey,

I can't open bspsrc, but i can open bspinfo.. i don't know why. I have the latest update of Java8.
:/

**Comment by TabTray** [comment]
are you opening bspsrc.**bat**?

**Comment by rihi** [comment]
Can you try launching the .bat in the cmd manually, to see if it prints any errors?
You can open the cmd by simply searching for it in the Windows search. Then just drag and drop bspsrc.bat onto the cmd and press enter.

**Comment by Koniglich** [comment]
I just did it, but no line is displayed, nothing happens... but then really nothing, not even it opens a window at the bottom of my windows and closes it immediately. I tested with bspinfo, it works directly by passing it through the CMD, that there is no problem.

**Comment by Koniglich** [comment]
Ok, update: so, oddly I had left it in my downloads folder, and because of that, bspsrc didn't launch... why? no idea. I had to move the files to a folder somewhere else for it to work
