### ISSUE TITLE
Suggestion: Missing File Restoration

### ISSUE THREAD

**Issue by TabTray** [ata4/bspsrc#157]
Not sure how possible this is, but a feature where BSPSource attempts to recover/extract any missing textures/models from maps would be greatly appreciated.
If you don't know what I mean, this is what happens to pl_breadspace from TF2, tool brush-less:
![image](https://user-images.githubusercontent.com/81453312/204164480-5f67d834-6ef7-48c7-8c41-d1293c5525f0.png)
![image](https://user-images.githubusercontent.com/81453312/204164497-cd70eb8c-638b-472a-930d-8c18697c3fba.png)
![image](https://user-images.githubusercontent.com/81453312/204164527-47f27777-14be-495b-83dc-47aa853b9afe.png)
![image](https://user-images.githubusercontent.com/81453312/204164604-e58438f0-ee8e-4710-870f-11904b170efd.png)
![image](https://user-images.githubusercontent.com/81453312/204164635-d0d1902a-3c4f-4441-9ce6-3d00d722803c.png)

**Comment by rihi** [comment]
I've never decompiled that map in question, but normally the first reason for missing textures/models, is that they are embedded into the bsp, so hammer doesn't know them.
If that is the case here aswell, please have look at the [FAQ](https://github.com/ata4/bspsrc/tree/v1.4.3#frequently-asked-questions). It tells you how to extract these resources and where to put them.

**Comment by TabTray** [comment]
Oh. Thank you!
