### ISSUE TITLE
Can't decompile 90% of post-steampipe maps

### ISSUE THREAD

**Issue by Flytnn** [ata4/bspsrc#16]
Hi, I'm getting this error whenever I try to decompile most post-steampipe maps. I'm the author of these trying to recover them, so I also cannot ask the author for a VMF copy as a work-around.

Progress:
[error] BspFileReader: Lump reading error in sprp: java.io.IOException: java.nio.BufferUnderflowException
[info] Loaded C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps\pl_genesis_a11.bsp
[info] BSP version: 20
[info] Game: Team Fortress 2
[info] Opened C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps\pl_genesis_a11_d.vmf
[info] Writing brushes and planes
[info] Writing displacements
[info] Writing entities
[info] Writing func_details
[info] Writing info_overlays
[info] Writing prop_statics
[warning] VmfWriter: Unclosed VMF chunk: entity
[info] Closed C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps\pl_genesis_a11_d.vmf
[info] Finished C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps\pl_genesis_a11.bsp
[error] BspSource: Decompiling error: java.lang.IndexOutOfBoundsException: Index: 5348, Size: 43
[info] Processed 1 file(s) in 1.1320 seconds

Errors & Warnings:
[error] BspFileReader: Lump reading error in sprp: java.io.IOException: java.nio.BufferUnderflowException
[warning] VmfWriter: Unclosed VMF chunk: entity
[error] BspSource: Decompiling error: java.lang.IndexOutOfBoundsException: Index: 5348, Size: 43

**Comment by ata4** [comment]
Oh dear, has the TF2 map format been changed again? I'll investigate...

**Comment by ata4** [comment]
Well, I can decompile your map and the latest official maps without errors. Make sure you're using the latest version 1.3.20.

**Comment by Flytnn** [comment]
Ha, wow, that was my problem all along. I was using 1.3.11, I feel silly now. Thanks though.
