### ISSUE TITLE
I can't check the box while installing the addon

### ISSUE THREAD

**Issue by neoforz** [ata4/bspsrc#167]
![image](https://user-images.githubusercontent.com/42904977/221650255-c47e5131-071d-4ddc-a871-34e77943eb76.png) says "module not found error: no module named "vdf"
What does it mean ?

**Comment by rihi** [comment]
I can't tell from the screenshot alone if the problem you are having is actually related to bspsrc or rather just the blender addon you are using.
You could try opening the map in Hammer first and if that doesn't work aswell I should be able to help you from there.
Alternatively, directly ask your question on the github page of the blender addon you are using. They should be able to help you with your specific error you are getting. I the github page should be [lasa01/io_import_vmf](https://github.com/lasa01/io_import_vmf).
