### ISSUE TITLE
Can bspsrc extract/decompile vscripts of CS:GO maps?

### ISSUE THREAD

**Issue by kamild1996** [ata4/bspsrc#168]
Title.
I'm trying to have a peek at the code of a certain CS:GO map. When I take a look at logic_ objects and try to "Open Source" of a listed script, nothing happens. I'm guessing bspsrc can't extract/decompile those?

**Comment by rihi** [comment]
I'm not too familiar with vscripts, but I would guess that they work similiar to custom textures/models, in that they are embedded as files into the bsp.
When extracting, check 'Extract embedded files' in the 'Other' tab. This will write all embedded resources to a folder alongside the decompiled .vmf.

**Comment by kamild1996** [comment]
Thank you, that does seem to work with vscripts too :)
