### ISSUE TITLE
build errors related to ata4 dependencies

### ISSUE THREAD

**Issue by Cokemonkey11** [ata4/bspsrc#17]
While building bspsrc with `ant -buildfile build.xml`, the following occurs:

https://gist.github.com/Cokemonkey11/474de88fe3c6f9bb1778

It seems there are many ata4 packages not included in the source. Is this intended?

**Comment by ata4** [comment]
I'm currently porting the project to Maven, which should hopefully fix all current problems and ease the building process.

**Comment by ata4** [comment]
Okay, the project is now using Maven. Try to build it again.

**Comment by Cokemonkey11** [comment]
On holiday, will take a look in a few days. Feel free to close.

**Comment by Cokemonkey11** [comment]
Compilation succeeds but nothing seems to happen when `target/bspsrc-1.3.20-SNAPSHOT.jar` is executed. 

It seems some build step of moving the jar file to the shell script is missing.
