### ISSUE TITLE
it doesn't launch properly

### ISSUE THREAD

**Issue by That-1-sniper-on-blu** [ata4/bspsrc#171]
when i installed the application it didn't run on the 1st-10th try. Reason:
"Windows couldn't find 'javaw'. certificate that the name was written correctfully, and try again."

**Comment by That-1-sniper-on-blu** [comment]
no screenshots were sent, because the text showing up is on brasilian portuguese.

**Comment by rihi** [comment]
You need to install java to run BspSource. See [Running BSPSource](https://github.com/ata4/bspsrc#running-bspsource)
