### ISSUE TITLE
Black Mesa Support?

### ISSUE THREAD

**Issue by Riomaki81** [ata4/bspsrc#18]
I've had mixed luck using BSPSource 1.3.20 to decompile maps from the Early Access version of Black Mesa.  While some work fine, such as bm_c1a2a (the start of Office Complex), others cause Hammer to become unresponsive while loading them, which has to be force killed through the task manager.  Attempting the operation again doesn't fix the problem.

I haven't seen any difference in BSPSource warnings between problematic maps and successful ones.  Both give these warnings (albeit with the invalid vector in different locations):

[warning] BspFileReader: Static prop struct size mismatch: expected 72, got 76 (using DStaticPropV10)
[warning] BspFileReader: Falling back to static prop v4
[warning] VmfWriter: Invalid vector: (3.67345E-40, 5.7424E-41, NaN)

For bm_c0a0b (the second level of Black Mesa Inbound) which fails, this is the complete progress output:

[info] Loading C:\Program Files (x86)\Steam\steamapps\common\Black Mesa\bms\maps\bm_c0a0b.bsp
[warning] BspFileReader: Static prop struct size mismatch: expected 72, got 76 (using DStaticPropV10)
[warning] BspFileReader: Falling back to static prop v4
[info] BSP version: 20
[info] Game: Black Mesa
[info] Writing brushes and planes
[info] Writing displacements
[info] Writing entities
[info] Writing func_details
[info] Writing info_overlays
[info] Writing prop_statics
[warning] VmfWriter: Invalid vector: (3.67345E-40, 5.7424E-41, NaN)
[info] Writing env_cubemaps
[info] Writing func_ladders
[info] Finished decompiling C:\Program Files (x86)\Steam\steamapps\common\Black Mesa\bms\maps\bm_c0a0b.bsp
[info] Processed 1 file(s) in 6.0290 seconds

**Comment by ata4** [comment]
Looks like Black Mesa is using a different format for prop_statics than what's internally defined for version 10. It looks like I'll need some test maps to fix it.

**Comment by Riomaki81** [comment]
Legally, I don't think I can provide the official map files.

However, thanks to your mentioning prop_statics, I think I figured out what causes it to break and have been able to recreate it in a custom map I'm making.

I tried building my custom map and decompiling the resulting BSP.  It loaded fine although it had a huge number of info_lighting entities with names like "sprp_lighting_###" (where ### is some number) sitting around the origin of the world.

I noticed on prop_statics, there are a few additional fields that are new to me.  These are "Generic (and use)lightmaps for this static prop," "Lightmap Resolution X" and "Lightmap Resolution Y."  I tried setting these to Yes, 128 and 128, then built the map.  When I decompiled and tried to open it, it crashed Hammer.

Comparing the two files for this one prop, this is the original VMF:

entity
{
	"id" "59152"
	"classname" "prop_static"
	"angles" "0 0 0"
	"fademindist" "-1"
	"fadescale" "1"
	"generatelightmaps" "1"
	"lightmapresolutionx" "128"
	"lightmapresolutiony" "128"
	"model" "models/props_questionableethics/conferencetable.mdl"
	"skin" "0"
	"solid" "6"
	"origin" "1760 384 256"
	editor
	{
		"color" "255 255 0"
		"visgroupshown" "1"
		"visgroupautoshown" "1"
		"logicalpos" "[0 15500]"
	}
}

This is the same prop in the decompiled version:

entity
{
	"id" "14984"
	"classname" "prop_static"
	"origin" "1760 384 256"
	"angles" "0 0 0"
	"skin" "0"
	"fademindist" "-1"
	"fademaxdist" "0"
	"solid" "6"
	"model" "models/props_questionableethics/conferencetable.mdl"
	"disableshadows" "0"
}

Here are links to these files.  Please let me know if these are useful to you.
canyontest.vmf
https://www.dropbox.com/s/4tcr87njs3g6tt1/canyontest.vmf?dl=0

canyontest.bsp (the result of building the above)
https://www.dropbox.com/s/xqpk7xzon2o1uey/canyontest.bsp?dl=0

canyontest_d.vmf (the result of decompiling the above)
https://www.dropbox.com/s/h3cd3skux81zqpg/canyontest_d.vmf?dl=0

**Comment by ata4** [comment]
Okay, I think I figured it out. Looks like the newer prop_static lump version 10 is now used in all newer Source games and that the older v10 format used in Counter-Strike: Global Offensive is actually game-specific. I updated the rules in the code to fix that. Thanks for the report and the test map!

**Comment by Riomaki81** [comment]
Cool, I look forward to trying this in the next build. :)

**Comment by ata4** [comment]
Originally, I also wanted to upload the decompiled test map to make sure it's working correctly now, but by server went down for a few days. Anyway, it's online again and here's the link:

http://ata4.info/downloads/tmp/canyontest_d.zip

**Comment by Riomaki81** [comment]
I can confirm that the level opens correctly and that the Lightmap settings on the conference room table are present and correct.

**Comment by ata4** [comment]
That's good, thanks for testing. I think I'll just build the current version and upload a new release, so you can test it on other maps.

**Comment by Riomaki81** [comment]
Sure, I'd be happy to take a look at it.

**Comment by Riomaki81** [comment]
Hi, I'm wondering if you've been able to compile a version with this fix yet.  It would be very helpful to Black Mesa mappers.

**Comment by ata4** [comment]
Sorry for the delay. I just uploaded 1.3.21, which contains the fix and should be able to decompile newer Black Mesa maps.

**Comment by Riomaki81** [comment]
I've tried it on several maps, including some complex ones that crashed before, and it seems to be working just fine!  Thanks! 


     On Monday, July 13, 2015 5:54 AM, ata4 <notifications@github.com> wrote:
   

 Sorry for the delay. I just uploaded 1.3.21, which contains the fix and should be able to decompile newer Black Mesa maps.—

**Comment by TomShkurti** [comment]
Still experiencing this issue in 1.3.23.
