### ISSUE TITLE
Invalid rotation and origin on some entity brushes

### ISSUE THREAD

**Issue by iBoonie** [ata4/bspsrc#184]
Current version: 1.4.5
BSP version: 20
Game: Team Fortress 2
Ive come across this on a few maps over the years where some entities are not where they are supposed to be, and the rotation is not correct. I have replaced the textures with dev textures so its easier to see. These walls are func_brush, but its also happening to other entities as well. I did see the rotfix, but that does not change anything in this situation.
![z8tNz](https://github.com/ata4/bspsrc/assets/62844047/cd0fc765-5d99-49fe-b5fe-ff7bc36aa0c2)

Some hammerID's which are incorrect:
3434354
3444757
3473329
3390446

General location if you want to take a peak in Hammer: -1820 3200 -960

Here is the ent file for one of the maps in question.
[rot.zip](https://github.com/ata4/bspsrc/files/14490642/rot.zip)

And the bsp if needed.
https://mega.nz/file/0OJmhSgQ#N5oL7mFSyQCbMOhn4ACohoKJXx1B9zCv7SY3xNJNUA4

**Comment by rihi** [comment]
Thank you for the comprehensive issue report!
I've addressed it in commit 985655b, and the fix will be incorporated into the upcoming release.
