### ISSUE TITLE
I need to decompile a GldSrc .bsp in .vmf format.

### ISSUE THREAD

**Issue by UrSick** [ata4/bspsrc#193]
I know that this program is not capable of this, but I would be grateful if you could tell me a way to do this.

**Comment by rihi** [comment]
I never worked with anything goldsrc related, so I can't really help you with this. I know there is a list of decompileres on the [valvesoftware wiki](https://developer.valvesoftware.com/wiki/Decompiling_Maps#GoldSrc) though. Also I'm sure there are probably a lot of tutorials if you search for them.
