### ISSUE TITLE
How can i re-enable func_detail merging again?

### ISSUE THREAD

**Issue by ALIEN31ITA** [ata4/bspsrc#194]
Hi, sorry for this question, but i really need this, since vbsp, will fail, and consider each func_detail their own.

was there ever a reason for disabling the auto-merge? or just preference...
Don't really wanna go between 2 decompiled versions and port the merged one's to the new one...

**Comment by rihi** [comment]
Internally we have an option to toggle this feature on and off. I changed the default a long time ago purely because of preference.
I didn't know we never had an option in the gui/cli to toggle this...
I've fixed this with dfa110ce, which will be included in the next release.
