### ISSUE TITLE
Could not find main class info.ata4.bspsrc.BspSourceLauncher

### ISSUE THREAD

**Issue by Mryo00** [ata4/bspsrc#26]
Hello. BSPSource is giving me this problem whenever I launch it. I fixed another problem previously, which was a bug with 'javaw', but now it's giving me this. Help? The class is there, but it won't work. I downloaded a new version and it still won't work.
![javaerror1](https://cloud.githubusercontent.com/assets/21036805/17663038/f2a6c0ba-632c-11e6-996e-b80f7599edd1.png)

**Comment by ivarvanwooning** [comment]
Can be fixed by updating to the latest version of Java and uninstalling the old version: https://www.java.com/en/download/
