### ISSUE TITLE
Disabling Areaports doesn't work properly

### ISSUE THREAD

**Issue by BenCat07** [ata4/bspsrc#30]
So, while messing with this decompiler, i firstly found out the areaportals are really broken due to bspsrc not properly loading them, so i tried to disable decompiling them.... i decompile my map, open it in hammer, and voila, area portals still are there. Could you maybe fix this? Thanks.

~BenCat07

**Comment by ata4** [comment]
I know, it's a bit misleading. but disabling that option currently doesn't disable areaportals *entirely*, it just stops the automatic conversion of areaportal brushes to entities. The process could probably reversed to actually delete detected areaportal brushes, but it would be quite erroneous.

**Comment by BenCat07** [comment]
Well then, could you maybe fix the area portals all being ONE pixel off?

**Comment by ata4** [comment]
Are they? Hm, let me check...

**Comment by BenCat07** [comment]
yep, it is a known issue, but you weren't here for quite a while, see https://github.com/ata4/bspsrc/issues/40 as reference

**Comment by ata4** [comment]
I know, I'm not an active mapper anymore, so I rarely get in touch with maps. But I'll create a new release soon, maybe I can fix that portal issue somehow...

**Comment by BenCat07** [comment]
Thank you very much. I don't know if you knew but this tool is what everyone uses to reverse the bsp file format, thanks for coming back to it

**Comment by rihi** [comment]
The issue with areaportal reallocation has since been fixed. I also agree that the gui option of "disabling" areaportals can be a bit misleading. I plan to do some changes to the ui someday when I have the time and I plan on improving that.

**Comment by BenCat07** [comment]
I never commented on this again for some reason, but thank you for the fixes! :)
