### ISSUE TITLE
Modern TF Map Resources not extracting again

### ISSUE THREAD

**Issue by DJPlaya** [ata4/bspsrc#31]
Just wanted to mention that BSP-Info and Source having quite some Problems showing or extracting the Resources of a Map im currently working with. BSP Info dosent even know what Game it was made for and wont show any Entitys.
(btw. BSPZip works)

here is an Sample (this is a dev map so the link updates quite often)> 
http://reinhardt.0x13.io/ingame/fastdl/drface/maps/dr_playstation_b53.bsp
http://reinhardt.0x13.io/ingame/fastdl/drface/maps/dr_playstation_b54.bsp
http://reinhardt.0x13.io/ingame/fastdl/drface/maps/dr_playstation_b55.bsp
http://reinhardt.0x13.io/ingame/fastdl/drface/maps/dr_playstation_b56.bsp
http://reinhardt.0x13.io/ingame/fastdl/drface/maps/dr_playstation_b57.bsp
http://reinhardt.0x13.io/ingame/fastdl/drface/maps/dr_playstation_b58.bsp
http://reinhardt.0x13.io/ingame/fastdl/drface/maps/dr_playstation_b59.bsp
http://reinhardt.0x13.io/ingame/fastdl/drface/maps/dr_playstation_b60.bsp

**Comment by rihi** [comment]
Hey, I believe your issue is should be fixed with version 1.4.1.
If your problem is not resolve with that new version, feel free to write here and I'll have another look at the problem.
You can get the release on the [releases page](https://github.com/ata4/bspsrc/releases).
