### ISSUE TITLE
How do you use the CLI?

### ISSUE THREAD

**Issue by Turbine1991** [ata4/bspsrc#33]
I've figured it out, I had to call upon the .jar file directly.

**Comment by DJPlaya** [comment]
Of course, the .bat is like a .cmd and contains already startup options

**Comment by Turbine1991** [comment]
It appeared to pass arguments over to the Jar file, I guess not.

The one thing which definitely does not have a CLI is extracting all of the map's contents. I had to compile HLExtract for Linux for that.
