### ISSUE TITLE
Still experiencing Black Mesa issues in 1.3.23

### ISSUE THREAD

**Issue by TomShkurti** [ata4/bspsrc#34]
Situation is identical to that outlined in detail [here](https://github.com/ata4/bspsrc/issues/18).

**Comment by TomShkurti** [comment]
Update- the vmfs produced are for the most part workable, provided that you open them in a text editor and manually remove the several hundred sprp_lighting_### entities produced.

I wouldn't say this *fixes* the issue, but it does massively downgrade its severity.

**Comment by TomShkurti** [comment]
Update- the vmfs produced are for the most part workable, provided that you open them in a text editor and manually remove the several hundred sprp_lighting_### entities produced.

I wouldn't say this *fixes* the issue, but it does massively downgrade its severity.

**Comment by Psycho-A** [comment]
It seems the project is already abandoned...

**Comment by lokkdokk** [comment]
Try send message to Ata4 http://steamcommunity.com/id/barracuda/

**Comment by darealshinji** [comment]
Another issue: Black Mesa multiplayer maps are automatically recognized as "Half-Life 2: Deathmatch"
