### ISSUE TITLE
VtM: Bloodlines areaportal decompiling issues

### ISSUE THREAD

**Issue by Psycho-A** [ata4/bspsrc#36]
I don't know, is the program still in developing... anyway.
Some areaportals got broken on decompiling - they got tens of repeated brushsides and it crashes Hammer editor on loading. For comparing, bspsrc v1.2.1 decompiles the same entities correctly with six brushsides. For reproducing error, just decompile the original sm_oceanhouse_2.bsp of game and walk with the Notepad to the latest areaportal entity. Removing it allows editor load map correctly.

**Comment by lokkdokk** [comment]
Попробуй отправить сообщение Ata4 http://steamcommunity.com/id/barracuda/
