### ISSUE TITLE
Could not open

### ISSUE THREAD

**Issue by Valmayu** [ata4/bspsrc#38]
So I tried opening the decompiler but I get this message: could not open C:\Users\-My Name-\Documents\New folder [2]\lib\386\jvm.cfg
Do you know what's going on?

**Comment by ata4** [comment]
Hm, hard to say... do you get that message simply by launching BSPSource? Then I'd guess it's a broken JVM installation. Maybe try to uninstall all Java installations you can find and install the most recent one.

**Comment by Tjmcnee** [comment]
It worked!! Thanks so much!
