### ISSUE TITLE
Broken areaportals.

### ISSUE THREAD

**Issue by spaztron64** [ata4/bspsrc#40]
Hi, I noticed that pretty much all maps that get decompiled have bad areaportals, in the sense of them not hiding what you can't see, but hiding everything behind it. Only getting thru the areaportal will allow you to see the rest of the map.
Sure this can be fixed in hammer editor by reconstructing the brushes manually, but it's time consuming and sometimes doesn't work.
Any way you can fix this?

Thanks in advance.

**Comment by legoj15** [comment]
I have noticed this too, I was wondering what was happening. A fix would be much appreciated

**Comment by BenCat07** [comment]
It's sinply them being off by one pixel and skyboxes having micro leaks

**Comment by rihi** [comment]
The areaportal reallocation process has been refactored with #46 and was published with version 1.4.0.
It should do much better now.
