### ISSUE TITLE
decompiling DOD maps

### ISSUE THREAD

**Issue by Jds1234** [ata4/bspsrc#5]
I have been decompiling DOD maps for my DOD:s server lately...

I notice bspsource is having issues detecting func_ladder entities, as at the moment it just recognises it as a nodrwaw brush, and does not change it back to func_ladder, leaves it as a nodraw brush, I have to go into the map(any DOD map) using hammer to change the brush back to func_ladder, also bspsource also doesnt change the texture back to toolinvisibleladder texture, it should do that...but it does not do that...should it be doing that?

**Comment by ata4** [comment]
Oh wow, this issue is almost three years old now...

Anyway, I had a look at the func_ladder problem and I think the entities should be written correctly in 1.3.19. I'm not sure about the texture issue, though. Maybe it has been fixed in one of the previous releases.
