### ISSUE TITLE
Unable to load,

### ISSUE THREAD

**Issue by FishyUberMuffin** [ata4/bspsrc#50]
The screen is showing me windows can not find javaw. How do I fix this?
![errordecompiler](https://user-images.githubusercontent.com/30203855/44267343-d360cd80-a1fb-11e8-8e36-39b35842f58c.PNG)

**Comment by ChazizYT** [comment]
You need "Java".

**Comment by rihi** [comment]
This happens when either java is not installed on your system or it isn't correctly setup with windows `Path` environment variable. There are a lot of resources online on how to install java, but I can recommend donwloading java from https://adoptium.net/de/temurin/releases/.
