### ISSUE TITLE
materials that have a i letter in it are replaced by ?

### ISSUE THREAD

**Issue by Fronkln** [ata4/bspsrc#51]
Because of this you get missing textures in hammer

**Comment by BlackShadow** [comment]
Bumping this.

**Comment by gitRihi** [comment]
Can anyone share a bsp where this problem occurs?
I could have a look at it and try to figure out whats going on.

**Comment by Fronkln** [comment]
@gitRihi Happens to all BSP's

**Comment by gitRihi** [comment]
Well, I can't manage to reproduce this issue. Does this maybe only apply to bsps of some game or is it more complex than just:
> materials that have 'i' letter in it are replaced by '?'

**Comment by Fronkln** [comment]
> Well, I can't manage to reproduce this issue. Does this maybe only apply to bsps of some game or is it more complex than just:
> 
> > materials that have 'i' letter in it are replaced by '?'

its probably related to language/culture of the computer

**Comment by BlackShadow** [comment]
> > Well, I can't manage to reproduce this issue. Does this maybe only apply to bsps of some game or is it more complex than just:
> > > materials that have 'i' letter in it are replaced by '?'
> 
> its probably related to language/culture of the computer

This may be the issue, because i can't no longer re-produce this issue, because i've added English keyboard. Still this issue should be fixed.

**Comment by gitRihi** [comment]
Ohhh, so it's about special characters like `î` in custom material names, that are converted to `?`?

**Comment by Fronkln** [comment]
Nah, it can sometimes be related to parsing, for example on C# (even though this is java) stuff like converting strings to lowercase causes i's to turn into ı's this could be a similiar case with this program here

**Comment by gitRihi** [comment]
Huh, seems like i learned something new. [The issue seems to be how the turkish language handles the uppercase/lowercase i](http://www.i18nguy.com/unicode/turkish-i18n.html).
The fix should be simple.

**Comment by Fronkln** [comment]
yep, exactly what i said earlier
