### ISSUE TITLE
Export as .map

### ISSUE THREAD

**Issue by BlackShadow** [ata4/bspsrc#60]
There should be an option to export as .map

**Comment by igdegoo** [comment]
.map is for goldsrc map files

**Comment by BlackShadow** [comment]
i know that was the reason why i requested this. This will help people while they trying to convert source to goldsource.

**Comment by BlackShadow** [comment]
I know. That was the reason why i requested this. This will help people if they trying to convert some assets in Source to Goldsource.

**Comment by xDShot** [comment]
[J.A.C.K.](https://jack.hlfx.ru/en/features.html) is able to load vmfs. Probably only feature missing is displacements, though there are none of them in goldsrc.

**Comment by BlackShadow** [comment]
I've tried load it trough J.A.C.K already and it failed.

**Comment by xDShot** [comment]
>I've tried load it trough J.A.C.K already and it failed.
Loads fine for me

**Comment by BlackShadow** [comment]
Okay, i've tried to decompile again and it's failed again. I've tried reinstalled J.A.C.K and working fine now.
