### ISSUE TITLE
a "simple bspsrc" for porting hl1 maps and models to hls

### ISSUE THREAD

**Issue by sixcentgeorge** [ata4/bspsrc#87]
i am not very good at mapping , mostly because i find the editors are not very friendly and viewing lines is not very easy for recognising objects.. but i like a lot playing with the entities file...that is quite the source of map file .
i wonder if you will make a specific bspsrc for helping porting old mods or maps of hl1 , with the help of their fgds and "direct rendering of map" [ like with crafty , bspviewer or bspview by botman ] to the half-life source single or multi player . i mean with the correct extraction for textures and creation "in the right folders" of the "right files" , same with models : static or monsters ...
i like using command line tools.. but i feel it "hard" to do it well with the use of three "all togethers" : bsp2map + mapfool + vtex .. with only a so shorty manual as :  https://developer.valvesoftware.com/wiki/Porting_Half-Life_maps .

i want to port old svencoop 3.0 maps , that i used in assault strike : https://www.moddb.com/members/sixcentgeorge/downloads
plus maps from a lot of mods : because i created the super long story extended of half-life..

it is a mix using plenty of maps from many mods ; i do not want to spoil too much but i think i can say something about the ingredients..: maps & mods , plus that it has an  "Epic Ending With a Two Kings Battle" [Tor vs Kingpin : king of vorts facing king of roswells] :

azure sheep
10/42
blue shift
29/30
decay
10/11
op4
18/36
pov
24/36
shl
16/24

106/179

hl
75/89

181/268 maps
it doubles half-life .. , i made a mod before assault strike named opposing life2life [ also at moddb ] where i added a lot of models to the maps coming from others mods or special hd pack.. i also want to use some in the compilation of the hl2 maps..
by now i try to get the help of gearbox or valve for the compilations of maps ..but if that fail..i would be pleased to have you and your help for doing the job.. 
may be the hl1 release will be free of charge but the ported to hl2 will be sold at steam at low price [ like the one of hls or hl ]
have a nice 2020 year

**Comment by rihi** [comment]
At least currently there are no real plans to support goldsrc maps in bspsrc, because its bsp format greatly differs from "normal" source games. This might change if I suddenly have a lot of time on my hands or if anybody else takes up the task, but for now this won't be implemented.
