### ISSUE TITLE
CS:GO Clip textures merge

### ISSUE THREAD

**Issue by darnias2** [ata4/bspsrc#96]
CS:GO has various clip textures with different $surfaceprops to have unique sounds, but when decompiled they are all reverted to the default clip texture.

**Comment by rihi** [comment]
This is sadly an issue which is really hard to fix.
The `$surfaceprops` property is not "baked" into the bsp but rather has to be retrieved by the actual texture name. So the decompiler would actually have to parse all textures availabe, to be able to make a good guess of the correct clip texture.
